DEV-212: Implement new UI v2.5 and disable a multi-level option
nexxt-intelligence/react-pivottable pull request #3
Opened 2020-10-21 18:54 UTC by dongwan-nexxt

Refer to the mock-up design [here](https://www.figma.com/file/ULeHkXGmOFP7KbiTVZf7YR/Crosstab-UI?node-id=0%3A1)

<img width="1241" alt="Screen Shot 2020-10-21 at 2 50 35 PM" src="https://user-images.githubusercontent.com/66445377/96769499-371f4c00-13ad-11eb-9bee-c80d4d425307.png">
<img width="543" alt="Screen Shot 2020-10-21 at 2 50 45 PM" src="https://user-images.githubusercontent.com/66445377/96769502-37b7e280-13ad-11eb-958f-173915bede1a.png">

2020-10-21 21:17 UTC, volodymyr-nexxt requested changes
Very nice!! Looks so much fresher, cleaner and nicer to use 🤩

A few nitpicks:
1) Header option's content should be aligned
![Screen Shot 2020-10-21 at 4 18 08 PM](https://user-images.githubusercontent.com/66445032/96785266-8f117f00-13bc-11eb-89c7-647856c2a3d7.png)

2) It'd be great if the full option's width was clickable (rn, you can only click text & radio btn icon)
![Screen Shot 2020-10-21 at 4 38 25 PM](https://user-images.githubusercontent.com/66445032/96785389-b8caa600-13bc-11eb-9499-2b1936f44875.png)

3) The stubs are not draggable... or is it part of V3?

2020-10-21 21:17 UTC, volodymyr-nexxt commented on src/TableRenderers.jsx
> +import React, {Fragment} from 'react';
```suggestion
import React from 'react';
```

No need to import `Fragment` explicitly since you're using it this way `<React.Fragment>`

2020-10-21 21:17 UTC, volodymyr-nexxt commented on src/pivottable.css
> +  border-radius: 3px;
let's stick with one style: either `white` or `#ffffff` across the styles

2020-10-21 21:17 UTC, volodymyr-nexxt commented on src/pivottable.css
> +/* When the checkbox is checked, add a blue background */
```suggestion
/* When the checkbox is checked, add a gray background */
```

2020-10-21 22:41 UTC, dongwan-nexxt commented
@volodymyr-nexxt Addressed all feedback ^.
- Regarding 3, yes I believe the functionality is part of v3

2020-10-22 14:36 UTC, volodymyr-nexxt approved these changes
LGTM, thanks!

2020-10-22 15:07 UTC, merged